global using DomainHelpers;
global using DomainHelpers.DataAnnotations;
global using DomainHelpers.Primitives;
global using DomainHelpers.Profiles;
global using DomainHelpers.Text;
global using System;
global using System.Collections.Generic;
global using System.Collections.Immutable;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using static System.Collections.Immutable.ImmutableArrayFactory;